### ISSUE TITLE
Create BlockRegex Parser Plugin

### ISSUE THREAD

**Issue by supertylerc** [supertylerc/network-static-analysis#11]
The `lineregex` plugin is a great, simple, beginner-friendly plugin because it only really requires 3 things of someone who wants to write a rule:

- basic understanding of YAML
- basic understanding of regular expressions
- worrying about only one single line instead of larger text documents

However, it has a noticeable drawback: it can't search across multiple lines for more complex pattern matching.  For example, you can't use it to ensure that all IGP interfaces have authentication configured.

A new parser (`blockregex`) could add a new field to the same rules that `lineregex` is using to indicate that the rule should only be used by the `blockregex` parser.  Then the plugin would take the lines, combined them into a `\n`-separated string, and use `re.search` only on the rules tagged as running under the `blockregex` parser.

The `blockregex` parser would need to be added to a new `profile` under the `SCA_FILE` configuration, and we'd need some updates in the CLI tool to do multiple (or all) profiles configured.

For an example rule, I envision something like the following.  Take the current TACACS+ key rule for example:

```yaml
---

rules:
  - title: Unencrypted/Cisco-7 TACACS+ Key
    pattern: tacacs-server key 7
    operator: in
    platforms:
      - nxos
    score: 1.0
    reason: The TACACS+ Key is not encrypted using the AES encryption feature in NX-OS.
```

Once the `blockregex` parser exists, that rule could be written as follows:

```yaml
---

rules:
  - title: Unencrypted/Cisco-7 TACACS+ Key
    pattern: tacacs-server key 7
    operator: in
    parsers:
      - blockregex
    platforms:
      - nxos
    score: 1.0
    reason: The TACACS+ Key is not encrypted using the AES encryption feature in NX-OS.
```

Obviously there's not much point in that particular case, but the above would restrict that rule to running only under the `blockregex` parser.  If the `parsers` key is omitted, then it would default to running only under `lineregex`.  `parsers` is a sequence because I can imagine some rules being run under multiple parsers.
